version: '3.8'

services:
  web:
    build: .
    container_name: maichart_web
    ports:
      - "5001:5001"
    volumes:
      - "./uploads:/app/uploads"
      - "./transcripts:/app/transcripts"
      - "./logs:/app/logs"
    env_file:
      - .env  
    environment:
      - FLASK_PORT=5001
    command: python app.py
    restart: unless-stopped

  transcription_worker:
    build: .
    container_name: maichart_transcription_worker
    volumes:
      - "./uploads:/app/uploads"
      - "./transcripts:/app/transcripts"
      - "./logs:/app/logs"
    env_file:
      - .env  
    command: python workers/transcription_worker.py
    restart: unless-stopped
    depends_on:
      - web